app/models.py
from app import db, login_manager
from flask_login import UserMixin
from datetime import datetime
from werkzeug.security import generate_password_hash, check_password_hash


class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), index=True, unique=True)
    email = db.Column(db.String(120), index=True, unique=True)
    password_hash = db.Column(db.String(128))
    tasks = db.relationship('Task', backref='author', lazy='dynamic')

    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)


class Task(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100), nullable=False)
    completed = db.Column(db.Boolean, default=False)
    timestamp = db.Column(db.DateTime, index=True, default=datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))


@login_manager.user_loader
def load_user(id):
    return User.query.get(int(id))

app/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField, TextAreaField
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError
from app.models import User
from email_validator import validate_email


class LoginForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    remember_me = BooleanField('Remember Me')
    submit = SubmitField('Sign In')


class RegistrationForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired(), Length(min=2, max=20)])
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    confirm_password = PasswordField('Confirm Password', validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField('Sign Up')

    def validate_username(self, username):
        user = User.query.filter_by(username=username.data).first()
        if user:
            raise ValidationError('That username is taken. Please choose a different one.')

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user:
            raise ValidationError('That email is taken. Please choose a different one.')


class TaskForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired(), Length(min=2, max=100)])
    description = TextAreaField('Description', validators=[Length(max=500)])
    submit = SubmitField('Add Task')

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager
from config import Config

db = SQLAlchemy()
migrate = Migrate()
login_manager = LoginManager()


def create_app():
    app = Flask(__name__)
    app.config.from_object(Config)

    db.init_app(app)
    migrate.init_app(app, db)
    login_manager.init_app(app)

    from app.routes import main

    app.register_blueprint(main)
    login_manager.login_view = 'main.login'

    return app

app/routes.py
from flask import render_template, redirect, url_for, flash, request, Blueprint
from flask_login import login_user, logout_user, current_user, login_required
from app import db
from app.models import User, Task
from app.forms import LoginForm, RegistrationForm, TaskForm
from app import login_manager
from app.forms import TaskForm

main = Blueprint('main', __name__)


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


@main.route('/')
def index():
    if current_user.is_authenticated:
        tasks = Task.query.filter_by(user_id=current_user.id).all()
        form = TaskForm()
        return render_template('index.html', title='Home', tasks=tasks, form=form)
    else:
        return render_template('index.html', title='Home')


@main.route('/tasks')
@login_required
def tasks():
    tasks = current_user.tasks.order_by(Task.timestamp.desc()).all()
    form = TaskForm()
    return render_template('tasks.html', title='Your Tasks', tasks=tasks, form=form)


@main.route('/tasks', methods=['POST'])
@login_required
def add_task():
    form = TaskForm()
    if form.validate_on_submit():
        task = Task(title=form.title.data, user_id=current_user.id)
        db.session.add(task)
        db.session.commit()
        flash('Task added successfully.', 'success')
    return redirect(url_for('main.tasks'))


@main.route('/tasks/<int:task_id>/delete', methods=['POST'])
@login_required
def delete_task(task_id):
    task = Task.query.get_or_404(task_id)
    if task.user_id != current_user.id:
        abort(403)
    db.session.delete(task)
    db.session.commit()
    flash('Task deleted.', 'success')
    return redirect(url_for('main.tasks'))


@main.route('/tasks/<int:task_id>/toggle', methods=['POST'])
@login_required
def toggle_task(task_id):
    task = Task.query.get_or_404(task_id)
    if task.user_id != current_user.id:
        abort(403)
    task.completed = not task.completed
    db.session.commit()
    return redirect(url_for('main.tasks'))


@main.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.tasks'))
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(username=form.username.data, email=form.email.data)
        user.set_password(form.password.data)
        db.session.add(user)
        db.session.commit()
        flash('Congratulations, you are now a registered user!', 'success')
        return redirect(url_for('main.login'))
    return render_template('register.html', title='Register', form=form)


@main.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.tasks'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user is None or not user.check_password(form.password.data):
            flash('Invalid email or password.', 'danger')
            return redirect(url_for('main.login'))
        login_user(user, remember=form.remember_me.data)
        next_page = request.args.get('next')
        return redirect(next_page) if next_page else redirect(url_for('main.tasks'))
    return render_template('login.html', title='Sign In', form=form)


@main.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.index'))

app/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Handlee&display=swap" rel="stylesheet">
    <title>Tododle</title>
  </head>
  <body>
  <div class="background-img">
    <div class="content-wrapper">
      <h1>Tododle</h1>
      <div class="container">
        {% block content %}{% endblock %}
        {% if current_user.is_authenticated %}
          <div class="text-center mt-4">
            <a href="{{ url_for('main.logout') }}" class="btn btn-secondary">Logout</a>
          </div>
        {% endif %}
      </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSGFpoO/uhnAd6fwl+bmVtvAiYx7/7Wz8XCp+HHAAK5GSLf2xlY" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-eMNCOe7tC1doHpGoJtKh7z7lGz7fuP4F8nfdFvAOA6Gg/z6Y5J6XqqyGXYM2ntX5" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-iZjIlOieX9lBxJxgm2Qae1AtyUarAu5tVf5R5gC7Vd5AIp9D7eJvlnevX+HD7EIZ" crossorigin="anonymous"></script>
   </div>
  </body>
</html>

app/templates/index.html
{% extends "base.html" %}

{% block content %}

  {% if not current_user.is_authenticated %}
    <h2>Sign in or register to start managing your tasks.</h2>
    <p>
      <a href="{{ url_for('main.login') }}" class="btn btn-primary login-register-btn">Login</a>
      <a href="{{ url_for('main.register') }}" class="btn btn-secondary login-register-btn">Register</a>

    </p>

{% else %}
<a href="{{ url_for('main.tasks') }}" class="btn btn-primary login-register-btn">My Tododle List</a>
{% endif %}
{% endblock %}

app/templates/login.html
{% extends "base.html" %}

{% block content %}
<div class="row justify-content-center mt-5">
  <div class="col-md-6 note-paper">
    <h2>Your personal online to-do list.</h2>
    <form method="post" action="{{ url_for('main.login') }}" novalidate>
      {{ form.hidden_tag() }}
      <div class="form-group">
        {{ form.email.label() }}
        {{ form.email(class="form-control") }}
      </div>
      <div class="form-group">
        {{ form.password.label() }}
        {{ form.password(class="form-control") }}
      </div>
      <div class="form-check">
        {{ form.remember_me(class="form-check-input") }}
        {{ form.remember_me.label(class="form-check-label") }}
      </div>
      <div class="text-center mt-3">
        {{ form.submit(class="btn btn-primary") }}
      </div>
    </form>
  </div>
</div>
{% endblock %}

app/templates/register.html
{% extends "base.html" %}

{% block content %}
<div class="row justify-content-center mt-5">
  <div class="col-md-6 note-paper">
    <h2>Your personal online to-do list.</h2>
    <form method="post" action="{{ url_for('main.register') }}" novalidate>
      {{ form.hidden_tag() }}
      <div class="form-group">
        {{ form.username.label() }}
        {{ form.username(class="form-control") }}
      </div>
      <div class="form-group">
        {{ form.email.label() }}
        {{ form.email(class="form-control") }}
      </div>
      <div class="form-group">
        {{ form.password.label() }}
        {{ form.password(class="form-control") }}
      </div>
      <div class="form-group">
        {{ form.confirm_password.label() }}
        {{ form.confirm_password(class="form-control") }}
      </div>
      <div class="text-center">
        {{ form.submit(class="btn btn-primary") }}
      </div>
    </form>
  </div>
</div>
{% endblock %}

app/templates/tasks.html
{% extends "base.html" %}

{% block content %}
  <div class="container">

    <form method="post" action="{{ url_for('main.add_task') }}" novalidate>
      {{ form.hidden_tag() }}
      <div class="form-group">
        {{ form.title.label() }}
        {{ form.title(class="form-control") }}
      </div>
      <div class="form-group">
        {{ form.description.label() }}
        {{ form.description(class="form-control") }}
      </div>
      <div class="text-center">
        {{ form.submit(class="btn btn-primary") }}
      </div>
    </form>

    {% if tasks %}
      <ul class="list-group mt-4">
        {% for task in tasks %}
          <li class="list-group-item">
            <h5 style="text-decoration: {% if task.completed %}line-through{% else %}none{% endif %};">{{ task.title }}</h5>
            <p style="text-decoration: {% if task.completed %}line-through{% else %}none{% endif %};">{{ task.description }}</p>
            <form action="{{ url_for('main.toggle_task', task_id=task.id) }}" method="POST" style="display:inline;">
              {{ form.csrf_token }}
              <button type="submit" class="btn btn-link p-0 m-0">{% if task.completed %}Mark as Incomplete{% else %}Mark as Complete{% endif %}</button>
            </form>
            <form action="{{ url_for('main.delete_task', task_id=task.id) }}" method="POST" style="display:inline;">
              {{ form.csrf_token }}
              <button type="submit" class="btn btn-link text-danger p-0 m-0">Delete</button>
            </form>
          </li>
        {% endfor %}
      </ul>
    {% else %}
      <div class="mt-4">
        <p>No tasks added yet.</p>
      </div>
    {% endif %}
  </div>
{% endblock %}